version: '3'

services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: on_failure
  
  todofront:
    depends_on:
      - todoback
    image: todofrontend
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
    restart: on_failure
    
  todotests:
    depends_on:
      - todoback
      - todofront
    image: todotests
    environment:
      - FRONT_HOST=todofront
    restart: on_failure